CREATE DATABASE COMMERCE_OLTP
GO

USE COMMERCE_OLTP
GO

CREATE TABLE CUSTOMER(
	IDCUSTOMER INT PRIMARY KEY IDENTITY,
	CUSTOMER_NAME VARCHAR(30) NOT NULL,
	SURNAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	GENDER CHAR(1) NOT NULL,
	BIRTHDAY DATE NOT NULL
)
GO

CREATE TABLE CUSTOMER_ADDRESS(
	IDADDRESS INT PRIMARY KEY IDENTITY,
	STREET VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	STATEE VARCHAR(20) NOT NULL,
	REGION VARCHAR(20) NOT NULL,
	ID_CUSTOMER INT UNIQUE
)
GO

CREATE TABLE SELLER(
	IDSELLER INT PRIMARY KEY IDENTITY,
	SELLER_NAME VARCHAR(30) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	EMAIL VARCHAR(60) UNIQUE NOT NULL,
	ID_MANAGER INT
)
GO

CREATE TABLE SUPPLIER(
	IDSUPPLIER INT PRIMARY KEY IDENTITY,
	SUPPLIER_NAME VARCHAR(50) NOT NULL
)
GO

CREATE TABLE PRODUCT(
	IDPRODUCT INT PRIMARY KEY IDENTITY,
	PRODUCT VARCHAR(100) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	AVARAGE_COST NUMERIC(10,2),
	ID_SUPPLIER INT,
	ID_CATEGORY INT

)
GO

CREATE TABLE CATEGORY(
	IDCATEGORY INT PRIMARY KEY IDENTITY,
	CATEGORY_NAME VARCHAR(30)
)
GO

CREATE TABLE INVOICE(
	IDINVOICE INT PRIMARY KEY IDENTITY,
	INVOICE_DATE DATE NOT NULL,
	TOTAL NUMERIC(10,2),
	ID_CUSTOMER INT,
	ID_SELLER INT,
	ID_PAYMENT INT
)
GO

CREATE TABLE INVOICE_ITEM(
	IDINVOICE_ITEM INT PRIMARY KEY IDENTITY,
	AMOUNT INT,
	TOTAL NUMERIC(10,2),
	ID_PRODUCT INT,
	ID_INVOICE INT
)
GO

CREATE TABLE PAYMENT_FORM(
	IDPAYMENT INT PRIMARY KEY IDENTITY,
	FORM VARCHAR(40) NOT NULL
)
GO