USE COMMERCE_OLTP
GO

INSERT INTO CATEGORY VALUES('LIVROS')
INSERT INTO CATEGORY VALUES('DVDS')
INSERT INTO CATEGORY VALUES('GAMES')
INSERT INTO CATEGORY VALUES('CELULARES')
INSERT INTO CATEGORY VALUES('INFORMATICA')
INSERT INTO CATEGORY VALUES('TV E AUDIO')
INSERT INTO CATEGORY VALUES('ELETRODOMESTICOS')
INSERT INTO CATEGORY VALUES('MOVEIS')
INSERT INTO CATEGORY VALUES('PASSAGENS')
GO