		/* LOAD SELLER */
		
		USE COMMERCE_OLTP
		GO

		INSERT INTO SELLER VALUES('EDUARDO SANTOS','M','ESANTOS.MANAGER@TERA.COM',NULL)
		INSERT INTO SELLER VALUES('RENATA MONTEIRO','F','RMONT@TERA.COM',1)
		INSERT INTO SELLER VALUES('JOAO NUNES','M','JNUNES@TERA.COM',1)
		INSERT INTO SELLER VALUES('CLARA MAFRA','F','CMAFRA@TERA.COM',1)
		INSERT INTO SELLER VALUES('GERALDO FRANCISCO','M','GFRANCISCO@TERA.COM',1)
		INSERT INTO SELLER VALUES('RODRIGO BIO','M','RBIO@TERA.COM',1)
		INSERT INTO SELLER VALUES('SERGIO AGUDO','M','SAGUDO@TERA.COM',1)
		INSERT INTO SELLER VALUES('PILAR SANCHES','F','PSANCHES@TERA.COM',1)
		INSERT INTO SELLER VALUES('MARCELO WITEMBERG','M','MWITEMBERG@TERA.COM',1)
		INSERT INTO SELLER VALUES('LILIAN SALINAS','F','LSALINAS@TERA.COM',NULL)
		INSERT INTO SELLER VALUES('RAFAELA LIMA','F','RLIMA@TERA.COM',9)
		INSERT INTO SELLER VALUES('CELIA TAVARES','F','CTAVARES@TERA.COM',9)
		INSERT INTO SELLER VALUES('HERMES MACEDO','M','HMACEDO@TERA.COM',9)
		INSERT INTO SELLER VALUES('SILVIO BAHIANA','M','SBAHIANA@TERA.COM',9)
		INSERT INTO SELLER VALUES('DEBORA ALMEIDA','F','DALMEIDA@TERA.COM',9)
		INSERT INTO SELLER VALUES('DAVID BORGES','M','DBORGES@TERA.COM',NULL)
		INSERT INTO SELLER VALUES('TERESA CRISTINA','F','TCRISTINA@TERA.COM',15)
		INSERT INTO SELLER VALUES('RODRIGO MARQUES','M','EMACHADO@TERA.COM',16)
		INSERT INTO SELLER VALUES('CARLOS SENRA','M','CSENRA@TERA.COM',16)
		INSERT INTO SELLER VALUES('FABIO AUGUSTO','M','FAUGUSTO@TERA.COM',16)
		INSERT INTO SELLER VALUES('WALLACE MOREIRA','M','WMOREIRA@TERA.COM',16)
		INSERT INTO SELLER VALUES('RENE CHIARI','M','RCHIARI@TERA.COM',16)
		INSERT INTO SELLER VALUES('ANTONIO JESUS','M','AJESUS@TERA.COM',16)
		INSERT INTO SELLER VALUES('PEDRO NUNES','M','PNUNES@TERA.COM',16)
		GO
