/* PAYMENT METHOD */

USE COMMERCE_OLTP
GO

INSERT INTO PAYMENT_FORM VALUES('Tranferência - Vista')
INSERT INTO PAYMENT_FORM VALUES('Depóito - Vista')
INSERT INTO PAYMENT_FORM VALUES('Boleto - Vista')
INSERT INTO PAYMENT_FORM VALUES('Cartão Master - Vencimento')
INSERT INTO PAYMENT_FORM VALUES('Cartão Master 2 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Master 3 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Master 4 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Master 5 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Master 10 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa - Vencimento')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 2 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 3 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 4 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 5 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 10 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão American - Vencimento')
INSERT INTO PAYMENT_FORM VALUES('Cartão American 5 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão American 10 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão American 12 vezes')
INSERT INTO PAYMENT_FORM VALUES('Pay Pall - Vista')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 2 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 3 vezes')
INSERT INTO PAYMENT_FORM VALUES('Cartão Visa 4 vezes')
INSERT INTO PAYMENT_FORM VALUES('Pay Pall - 5 vezes')
INSERT INTO PAYMENT_FORM VALUES('Pay Pall - 12 vezes')
INSERT INTO PAYMENT_FORM VALUES('Pagamento Seguro Web - Vista')
GO



