/* COMPLETING THE INVICE TABLE */



DECLARE
	@ID_CUSTOMER INT, @ID_SELLER INT, @ID_PAYMENT INT, @INVOICE_DATE DATE

BEGIN
	SET @ID_CUSTOMER = 
	(SELECT TOP 1 IDCUSTOMER FROM CUSTOMER ORDER BY NEWID())

	SET @ID_SELLER = 
	(SELECT TOP 1 IDSELLER FROM SELLER ORDER BY NEWID())

	SET @ID_PAYMENT = 
	(SELECT TOP 1 IDPAYMENT FROM PAYMENT_FORM ORDER BY NEWID())

	SET @INVOICE_DATE = (SELECT
						CONVERT(DATE, CONVERT(VARCHAR(21), '2020/' + 
						CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*12)) + 1) + '/' +
						CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*27)) + 1))))


	INSERT INTO INVOICE(ID_CUSTOMER,ID_SELLER,ID_PAYMENT,INVOICE_DATE) VALUES
	(@ID_CUSTOMER, @ID_SELLER, @ID_PAYMENT, @INVOICE_DATE)


END
GO 7800




DECLARE
	@ID_CUSTOMER INT, @ID_SELLER INT, @ID_PAYMENT INT, @INVOICE_DATE DATE

BEGIN
	SET @ID_CUSTOMER = 
	(SELECT TOP 1 IDCUSTOMER FROM CUSTOMER ORDER BY NEWID())

	SET @ID_SELLER = 
	(SELECT TOP 1 IDSELLER FROM SELLER ORDER BY NEWID())

	SET @ID_PAYMENT = 
	(SELECT TOP 1 IDPAYMENT FROM PAYMENT_FORM ORDER BY NEWID())

	SET @INVOICE_DATE = (SELECT
						CONVERT(DATE, CONVERT(VARCHAR(21), '2021/' + 
						CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*12)) + 1) + '/' +
						CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*27)) + 1))))


	INSERT INTO INVOICE(ID_CUSTOMER,ID_SELLER,ID_PAYMENT,INVOICE_DATE) VALUES
	(@ID_CUSTOMER, @ID_SELLER, @ID_PAYMENT, @INVOICE_DATE)


END
GO 8000




DECLARE
	@ID_CUSTOMER INT, @ID_SELLER INT, @ID_PAYMENT INT, @INVOICE_DATE DATE

BEGIN
	SET @ID_CUSTOMER = 
	(SELECT TOP 1 IDCUSTOMER FROM CUSTOMER ORDER BY NEWID())

	SET @ID_SELLER = 
	(SELECT TOP 1 IDSELLER FROM SELLER ORDER BY NEWID())

	SET @ID_PAYMENT = 
	(SELECT TOP 1 IDPAYMENT FROM PAYMENT_FORM ORDER BY NEWID())

	SET @INVOICE_DATE = (SELECT
						CONVERT(DATE, CONVERT(VARCHAR(21), '2022/' + 
						CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*12)) + 1) + '/' +
						CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*27)) + 1))))


	INSERT INTO INVOICE(ID_CUSTOMER,ID_SELLER,ID_PAYMENT,INVOICE_DATE) VALUES
	(@ID_CUSTOMER, @ID_SELLER, @ID_PAYMENT, @INVOICE_DATE)


END
GO 8400

