/* INVOICE ITEM */

USE COMMERCE_OLTP
GO

DECLARE
		@ID_PRODUCT INT,
		@ID_INVOICE INT,
		@AMOUNT INT,
		@VALUE NUMERIC(10,2),
		@TOTAL NUMERIC(10,2)

BEGIN
		SET @ID_PRODUCT = 
		(SELECT TOP 1 IDPRODUCT FROM PRODUCT ORDER BY NEWID())

		SET @ID_INVOICE = 
		(SELECT TOP 1 IDINVOICE FROM INVOICE ORDER BY NEWID())

		SET @AMOUNT = 
		(SELECT ROUND(RAND() * 4 + 1, 0))

		SET @VALUE = 
		(SELECT VALOR FROM PRODUCT WHERE IDPRODUCT = @ID_PRODUCT)

		SET @TOTAL = @AMOUNT * @VALUE

		INSERT INTO INVOICE_ITEM(ID_PRODUCT, ID_INVOICE, AMOUNT, TOTAL)
		VALUES (@ID_PRODUCT, @ID_INVOICE, @AMOUNT, @TOTAL)

END
GO 50000

/* CHECKING THE NOTES THAT RUN OUT OF ITEMS */

SELECT IDINVOICE FROM INVOICE
WHERE IDINVOICE NOT IN(SELECT ID_INVOICE FROM INVOICE_ITEM)
GO


SELECT * FROM INVOICE_ITEM
GO

/* CREATING A CURSOR TO FILL OUT NOTES THAT HAD NO ITEMS */

CREATE PROCEDURE CAD_INVOICE AS

DECLARE C_INVOICE CURSOR FOR
	SELECT IDINVOICE FROM INVOICE
	WHERE IDINVOICE NOT IN(SELECT ID_INVOICE FROM INVOICE_ITEM)

DECLARE @IDINVOICE INT,
		@ID_PRODUCT INT,
		@VALUE DECIMAL(10,2), 
		@TOTAL DECIMAL(10,2)


OPEN C_INVOICE

FETCH NEXT FROM C_INVOICE
INTO @IDINVOICE

WHILE @@FETCH_STATUS = 0
BEGIN
	
			SET @ID_PRODUCT = 
			(SELECT TOP 1 IDPRODUCT FROM PRODUCT ORDER BY NEWID())
			SET @VALUE = (SELECT VALOR FROM PRODUCT
			        	  WHERE IDPRODUCT = @ID_PRODUCT)
			SET @TOTAL = @VALUE
	
			INSERT INTO INVOICE_ITEM(ID_PRODUCT,ID_INVOICE,AMOUNT,TOTAL)
			 VALUES(@ID_PRODUCT,@IDINVOICE,1,@TOTAL)
		
	FETCH NEXT FROM C_INVOICE
	INTO @IDINVOICE
	
END

CLOSE C_INVOICE
DEALLOCATE C_INVOICE
GO

EXEC CAD_INVOICE
GO

/* CREATING A VIEW TO VERIFY THE ITEMS REQUESTED */

CREATE VIEW V_INVOICE_ITEM AS
SELECT	ID_INVOICE AS "INVOICE",
		PRODUCT,
		VALOR,
		AMOUNT,
		TOTAL AS "ITEM TOTAL"
FROM PRODUCT
INNER JOIN INVOICE_ITEM
ON IDPRODUCT = ID_PRODUCT
GO

SELECT * FROM INVOICE_ITEM
SELECT * FROM V_INVOICE_ITEM
ORDER BY 1
GO

SELECT * FROM INVOICE

SELECT C.CUSTOMER_NAME, C.SURNAME,C.GENDER,N.INVOICE_DATE,N.IDINVOICE,P.PRODUCT,N.TOTAL

FROM CUSTOMER C
INNER JOIN INVOICE N
ON C.IDCUSTOMER = N.ID_CUSTOMER
INNER JOIN INVOICE_ITEM I
ON N.IDINVOICE = I.ID_INVOICE
INNER JOIN PRODUCT P
ON P.IDPRODUCT = I.ID_PRODUCT
ORDER BY 5
GO

