/* INVOICE UPDATE */

CREATE VIEW V_INVOICE AS
SELECT ID_INVOICE, SUM(TOTAL) AS SOMA
FROM INVOICE_ITEM
GROUP BY ID_INVOICE
GO

SELECT * FROM V_INVOICE
WHERE ID_INVOICE = 1000
GO

CREATE VIEW V_LOAD_INVOICE AS
SELECT IDINVOICE , N.TOTAL TOTALINVOICE, I.SOMA
FROM INVOICE N
INNER JOIN V_INVOICE I
ON IDINVOICE = ID_INVOICE
GO

SELECT * FROM V_LOAD_INVOICE
GO

UPDATE V_LOAD_INVOICE SET TOTALINVOICE = SOMA
GO

/* QUERY IN THE OLTP ENVIRONMENT */

SELECT C.CUSTOMER_NAME,C.SURNAME AS "CUSTOMER", I.INVOICE_DATE, I.IDINVOICE,P.PRODUCT,I.TOTAL
FROM CUSTOMER C
INNER JOIN INVOICE I
ON C.IDCUSTOMER = I.ID_CUSTOMER
INNER JOIN INVOICE_ITEM I
ON N.IDINVOICE = D.ID_INVOICE
INNER JOIN PRODUCT P
ON P.IDPRODUCT = D.ID_PRODUCT
ORDER BY 5
GO