/* CREATION OF THE STAGE AREA */

CREATE DATABASE COMMERCE_STAGE
GO

USE COMMERCE_STAGE
GO

CREATE TABLE ST_CUSTOMER(
	IDCUSTOMER INT DEFAULT NULL,
	CUSTOMER_NAME VARCHAR(100) DEFAULT NULL,
	GENDER VARCHAR(20) DEFAULT NULL,
	BIRTHDAY DATE DEFAULT NULL,
	CITY VARCHAR(100) DEFAULT NULL,
	STATEE VARCHAR(10) DEFAULT NULL,
	REGION VARCHAR(20) DEFAULT NULL
)
GO

CREATE TABLE ST_SELLER(
	IDSELLER INT DEFAULT NULL,
	SALLER_NAME VARCHAR(50) DEFAULT NULL,
	GENDER VARCHAR(20) DEFAULT NULL,
	IDMANAGER INT DEFAULT NULL
)
GO

CREATE TABLE ST_CATEGORY(
	IDCATEGOTY INT DEFAULT NULL,
	CATEGORY_NAME VARCHAR(50) DEFAULT NULL
)
GO

CREATE TABLE ST_SUPPLIER(
	IDSUPPLIER INT DEFAULT NULL,
	SUPPLIER_NAME VARCHAR(100) DEFAULT NULL
)
GO

CREATE TABLE ST_PRODUCT(
	IDPRODUCT INT DEFAULT NULL,
	PRODUCT_NAME VARCHAR(50) DEFAULT NULL,
	VALOR NUMERIC(10,2) DEFAULT NULL,
	AVARAGE_COST NUMERIC(10,2) DEFAULT NULL,
	ID_CATEGORY INT DEFAULT NULL
)
GO

CREATE TABLE ST_INVOICE(
	IDINVOICE INT DEFAULT NULL
)
GO

CREATE TABLE ST_PAYMENT(
	IDPAYMENT INT DEFAULT NULL,
	PAYMENT_FORM VARCHAR(30) DEFAULT NULL
)
GO

CREATE TABLE ST_FATO(
	IDCUSTOMER INT DEFAULT NULL,
	IDSELLER INT DEFAULT NULL,
	IDPRODUCT INT DEFAULT NULL,
	IDSUPPLIER INT DEFAULT NULL,
	IDINVOICE INT DEFAULT NULL,
	IDPAYMENT INT DEFAULT NULL,
	AUMONT INT DEFAULT NULL,
	TOTAL_ITEM NUMERIC(10,2) DEFAULT NULL,
	DATE DATE DEFAULT NULL,
	COST_TOTAL NUMERIC(10,2) DEFAULT NULL,
	PROFIT_TOTAL NUMERIC(10,2) DEFAULT NULL
)
GO