/* CURSOR CAMEL CASE */

CREATE PROCEDURE CAMEL_CASE AS
DECLARE C_NAMES CURSOR FOR
SELECT IDPRODUCT, PRODUCT_NAME
FROM ST_PRODUCT

DECLARE @IDPRODUCT INT,
		@WORD VARCHAR(50),
	    @STRINGTOTAL VARCHAR(5000),
		@BEGIN INT,
		@END INT	

OPEN C_NAMES
FETCH NEXT FROM C_NAMES INTO
@IDPRODUCT, @WORD

WHILE @@FETCH_STATUS = 0

BEGIN

	SET @WORD = LOWER(@WORD)
	SET @BEGIN = 2
	SET @END = LEN(@WORD)
	SET @STRINGTOTAL = UPPER(LEFT(@WORD,1))

	WHILE @BEGIN <= @END
		
		BEGIN
				IF SUBSTRING(@WORD,@BEGIN,1) = ' '
				BEGIN 
					SELECT @BEGIN = @BEGIN + 1
					SELECT @STRINGTOTAL = @STRINGTOTAL + ' ' + 
					UPPER(SUBSTRING(@WORD,@BEGIN,1))
				END
				ELSE
				BEGIN
					SELECT @STRINGTOTAL = @STRINGTOTAL + 
					SUBSTRING(@WORD,@BEGIN,1)
				END
				
				SELECT @BEGIN = @BEGIN + 1
				
		END

		UPDATE ST_PRODUCT SET PRODUCT_NAME = @STRINGTOTAL
		WHERE IDPRODUCT = @IDPRODUCT

		FETCH NEXT FROM C_NAMES INTO
		@IDPRODUCT, @WORD
END

CLOSE C_NAMES
DEALLOCATE C_NAMES
GO