/* USEFUL VIEWS */

USE COMMERCE_OLTP
GO

SELECT CUSTOMER_NAME, IDINVOICE, INVOICE_DATE, IDINVOICE_ITEM, PRODUCT, VALOR, AMOUNT, I.TOTAL
FROM CUSTOMER
INNER JOIN INVOICE I
ON IDCUSTOMER = ID_CUSTOMER
INNER JOIN INVOICE_ITEM
ON ID_INVOICE = IDINVOICE
INNER JOIN PRODUCT
ON IDPRODUCT = ID_PRODUCT
ORDER BY 2
GO

SELECT * FROM INVOICE_ITEM

SELECT * FROM INVOICE