USE COMMERCE_OLTP
GO

DROP VIEW SALES_REPORT
GO

CREATE VIEW SALES_REPORT AS
SELECT	C.CUSTOMER AS IDCUSTOMER,
		S.IDSELLER AS IDSELLER,
		P.PRODUCT AS IDPRODUCT,
		SU.SUPPLIER AS IDSUPPLIER,
		I.INVOICE AS IDINVOICE,
		IDPAYMENT AS IDPAYMENT,
		ITEM.AMOUNT AS AMOUNT,
		(ITEM.AMOUNT * P.AVARAGE_COST) AS TOTAL_COST,
	    (ITEM.TOTAL - (ITEM.QUANTIDADE * P.AVARAGE_COST)) AS PROFIT_TOTAL,
		ITEM.TOTAL AS TOTAL_ITEM,
	    I.INVOICE_DATE AS DATE

FROM INVOICE I
INNER JOIN INVOICE_ITEM ITEM ON (I.IDINVOICE = ITEM.ID_INVOICE)
INNER JOIN CUSTOMER C ON (C.IDCUSTOMER = I.ID_CUSTOMER)
INNER JOIN SELLER S ON (S.IDSELLER = I.ID_SELLER)
INNER JOIN PRODUCT P ON (P.IDPRODUCT = ID_PRODUCT)
INNER JOIN PAYMENT_FORM PAY ON (PAY.IDPAYMENT = I.ID_PAYMENT)
INNER JOIN SUPPLIER SU ON (SU.IDSUPPLIER = P.ID_SUPPLIER)
GO

SELECT * FROM SALES_REPORT
ORDER BY IDINVOICE
GO
