/* DATA WAREHOUSE */

CREATE DATABASE COMMERCE_DW
GO

USE COMMERCE_DW
GO

CREATE TABLE DIM_SELLER(
	IDSK INT PRIMARY KEY IDENTITY,
	IDSELLER INT,
	BEGINING DATETIME,
	ENDING DATETIME,
	SELLER_NAME VARCHAR(50),
	GENER VARCHAR(20),
	IDMANAGER INT
)
GO

CREATE TABLE DIM_INVOICE(
	IDSK INT PRIMARY KEY IDENTITY,
	IDINVOICE INT
)
GO

CREATE TABLE DIM_PAYMENT(
	IDSK INT PRIMARY KEY IDENTITY,
	IDPAYMENT INT,
	FORM VARCHAR(30)
)
GO

CREATE TABLE DIM_CUSTOMER(
	IDSK INT PRIMARY KEY IDENTITY,
	IDCUSTOMER INT,
	BEGING DATETIME,
	ENDING DATETIME,
	CUSTOMER_NAME VARCHAR(100),
	GENDER VARCHAR(20),
	BIRTHDAY DATE,
	CITY VARCHAR(100),
	STATEE VARCHAR(10),
	REGION VARCHAR(20)
)
GO

CREATE TABLE CATEGORY(
	IDCATEGORY INT PRIMARY KEY,
	CATEGORY_NAME VARCHAR(50)
)
GO

CREATE TABLE DIM_PRODUCT(
	IDSK INT PRIMARY KEY IDENTITY,
	IDPRODUCT INT,
	BEGING DATETIME,
	ENDING DATETIME,
	PRODUCT_NAME VARCHAR(50),
	VALUE_PRODUCT NUMERIC(10,2) DEFAULT NULL,
	AVARAGE_COST NUMERIC(10,2) DEFAULT NULL,
	ID_CATEGORY INT,
	FOREIGN KEY(ID_CATEGORY) REFERENCES
	CATEGORY(IDCATEGORY)
)
GO

CREATE TABLE DIM_SUPPLIER(
	IDSK INT PRIMARY KEY IDENTITY,
	IDSUPPLIER INT,
	BEGING DATETIME,
	ENDING DATETIME,
	SUPPLIER_NAME VARCHAR(30)
)
GO

CREATE TABLE DIM_TIME( 
    IDSK INT PRIMARY KEY IDENTITY, 
    DATE DATE, 
    DAY CHAR(2), 
    WEEKDAY VARCHAR(10), 
    MOUNTH CHAR(2), 
    MOUNTHNAME VARCHAR(10), 
    QUARTER TINYINT, 
    QUARTERNAME VARCHAR(10), 
    YEAR CHAR(4), 
	SEASON VARCHAR(20),
	WEEKEND CHAR(3),
	FULLDATE VARCHAR(10)
) 
GO 

CREATE TABLE FATO(
	IDNOTA INT REFERENCES DIM_NOTA(IDSK),
	IDCLIENTE INT REFERENCES DIM_CLIENTE(IDSK),
	IDVENDEDOR INT REFERENCES DIM_VENDEDOR(IDSK),
	IDFORMA INT REFERENCES DIM_FORMA(IDSK),
	IDPRODUTO INT REFERENCES DIM_PRODUTO(IDSK),
	IDFORNECEDOR INT REFERENCES DIM_FORNECEDOR(IDSK),
	IDTEMPO INT REFERENCES DIM_TEMPO(IDSK),
	QUANTIDADE INT,
	TOTAL_ITEM NUMERIC(10,2),
	CUSTO_TOTAL NUMERIC(10,2),
	LUCRO_TOTAL NUMERIC(10,2)
)
GO