/* LOAD TIME DIMENSION */

-- CURRENT DATE 

PRINT CONVERT(VARCHAR,GETDATE(),113)

--CHANGE THE INCREMENT TO START AT 5000
--FOR THE POSSIBILITY OF EARLIER DATES

DBCC CHECKIDENT (DIM_TIME, RESEED, 5000)

-- INSERTING DATA INTO THE DIMENSION

DECLARE	 @DATEBEGIN DATETIME
		,@DATEEND DATETIME
		,@DATE DATETIME

PRINT GETDATE()
	SELECT	@DATEBEGIN = '1/1/1950' 
			,@DATEEND = '1/1/2050'

	SELECT @DATE = @DATEBEGIN 

WHILE @DATE < @DATEEND
	
	BEGIN
		INSERT INTO DIM_TIME
		(	DATE,
			DAY,
			WEEKDAY,
			MONTH,
			MONTHNAME,
			QUARTER,
			QUARTERNAME,
			YEAR

		)

		SELECT @DATE AS DATE, DATEPART(DAY,@DATE) AS DAY,

			CASE DATEPART(DW, @DATE) 
            
					WHEN 1 THEN 'Sunday'
					WHEN 2 THEN 'Monday' 
					WHEN 3 THEN 'Tuesday' 
					WHEN 4 THEN 'Wednesday' 
					WHEN 5 THEN 'Thursday' 
					WHEN 6 THEN 'Friday' 
					WHEN 7 THEN 'Saturday'

			END AS WEEKDAY,

			DATEPART(MONTH,@DATE) AS MONTH,
				/* CASE DATENAME(MONTH,@DATE) 
		
			 END AS MONTHNAME, */


			DATEPART(qq,@DATE) QUARTER,
				CASE DATEPART(qq,@DATE)
					WHEN 1 THEN 'FIRST'
					WHEN 2 THEN 'SECOND'
					WHEN 3 THEN 'THIRD'
					WHEN 4 THEN 'FOURTH'
			END AS QUARTERNAME,

			DATEPART(YEAR,@DATE) YEAR

		SELECT @DATE = DATEADD(dd,1,@DATE)
	END

UPDATE DIM_TIME 
	SET DAY = '0' + DAY 
	WHERE LEN(DAY) = 1 

UPDATE DIM_TIME 
	SET MONTH = '0' + MONTH 
	WHERE LEN(MONTH) = 1 

UPDATE DIM_TIME 
	SET COMPLETEDATE = YEAR + MONTH + DAY 
GO

SELECT * FROM DIM_TIME

----------WEEKENDS AND HOLIDAYS-----------


DECLARE C_TIME CURSOR FOR	
	SELECT IDSK, DATECOMPLITE, WEEKDAY, YEAR FROM DIM_TIME
DECLARE			
			@ID INT,
			@DATE varchar(10),
			@WEEKDAY VARCHAR(20),
			@YEAR CHAR(4),
			@WEEKEND CHAR(3),
			@SEASON VARCHAR(15)
					
OPEN C_TIME
	FETCH NEXT FROM C_TIME
	INTO @ID, @DATE, @WEEKDAY, @YEAR
WHILE @@FETCH_STATUS = 0

BEGIN
			
			 IF @WEEKDAY in ('Sunday','SATURDAY') 
				SET @WEEKEND = 'Sim'
			 ELSE 
				SET @@WEEKEND = 'No'
				
				
				--SEASONS

				IF @DATE BETWEEN CONVERT(CHAR(4),@YEAR)+'0923' 
			AND CONVERT(CHAR(4),@YEAR)+'1220'
				SET @SEASON = 'Spring'
				ELSE IF @DATE BETWEEN CONVERT(CHAR(4),@YEAR)+'0321' 
			AND CONVERT(CHAR(4),@ANO)+'0620'
				SET @SEASON = 'Fall'
				ELSE IF @DATE BETWEEN CONVERT(CHAR(4),@YEAR)+'0621' 
			AND CONVERT(CHAR(4),@YEAR)+'0922'
				SET @SEASON = 'Winter'
				ELSE -- @data between 21/12 e 20/03
				SET @SEASON = 'Summer'
				
				--WEEKENDS

			UPDATE DIM_TIME SET WEEKEND = @WEEKEND
			WHERE IDSK = @ID

			--UPDATING

			UPDATE DIM_TIME SET SEASONYEAR = @SEASON
			WHERE IDSK = @ID
		
	FETCH NEXT FROM C_TIME
	INTO @ID, @DATE, @WEEKDAY, @YEAR	
END
CLOSE C_TIME
DEALLOCATE C_TIME
GO