/* CONNECT TO DW */

USE COMMERCE_OLTP
GO

-- PROCEDURE

CREATE PROC LOAD_FACT
AS

DECLARE @END DATETIME
DECLARE @BEGGIN DATETIME

SELECT @END = MAX(DATE)
FROM COMMERCE_DW.dbo.DIM_TIME T

SELECT @BEGGIN = MAX(DATE)
FROM COMMERCE_DW.dbo.FACT FT
JOIN COMMERCE_DW.dbo.DIM_TIME T ON (FT.IDTIME=T.IDSK)

IF @BEGGIN IS NULL
BEGIN
	SELECT @BEGGIN = MIN(DATA)
	FROM COMMERCE_DW.dbo.DIM_TIME T

END


INSERT INTO COMMERCE_DW.dbo.FACT(
	IDINVOICE,
	IDCUSTOMER,
	IDSELLER,
	IDPAYMENT,
	IDSUPPLIER,
	IDPRODUCT,
	IDTIME,
	AUMONT,
	ITEM_TOTAL,
	COST_TOTAL,
	PROFIT_TOTAL
)
SELECT

	I.IDSK AS IDINVOICE,
	C.IDSK AS IDCUSTOMER,
	S.IDSK AS IDSELLER,
	P.IDSK AS IDPAYMENT,
	SP.IDSK AS IDSUPPLIER,
	P.IDSK AS IDPRODUCT,	
	T.IDSK as IDTIME,
	P.AMOUNT,
	P.ITEM_TOTAL,
	P.COST_TOTAL,
	P.PROFIT_TOTAL

FROM
	COMMERCE_STAGE.dbo.ST_FATO F

	INNER JOIN dbo.DIM_FORM FO
	ON (F.IDPAYMENT=FO.IDPAYMENT)

	INNER JOIN DBO.DIM_INVOICE DI
	ON (F.INVOICE=DI.IDINVOICE)

	INNER JOIN DBO.DIM_SUPPLIER DSP
	ON (F.IDSUPPLIER=DSP.IDSUPPLIER AND (DSP.BEGGIN <= F.DATE AND (DSP.END >= F.DATA) OR (DSP.FIM IS NULL)))

	INNER JOIN DBO.CUSTOMER C
	ON (F.IDCUSTOMER=C.IDCUSTOMER AND (C.BEGGIN <= F.DATE AND (C.FIM >= F.END) OR (C.END IS NULL)))

	INNER JOIN DBO.DIM_SELLER V
	ON (F.IDSELLER=V.IDSELLER AND (V.BEGGIN <= F.DATE AND (V.END >= F.DATE) OR (V.END IS NULL)))

	INNER JOIN DBO.DIM_PRODUCT P
	ON (F.IDPRODUCT=P.IDPRODUCT AND (P.BEGGIN <= F.DATE AND (P.END >= F.DATE) OR (P.END IS NULL)))

	INNER JOIN DBO.DIM_TEMPO T
		ON (CONVERT(VARCHAR, T.DATE,102) = CONVERT(VARCHAR,	F.DATE,102))	
		WHERE F.DATE BETWEEN @BEGGIN AND @END

GO