SELECT REGION, YEAR,
SUM(PROFIT_TOTAL) AS PROFIT,
SUM(AMOUNT) AS AMO,
SUM(ITEM_TOTAL) AS TOTAL,
SUM(COST_TOTAL) AS COST
FROM DIM_CUSTOMER
INNER JOIN FACT F
ON IDSK = F.IDCUSTOMER
INNER JOIN DIM_TIME T
ON T.IDSK = IDTIME
GROUP BY REGION, YEAR
ORDER BY 1, 2