/* VIEW */

USE COMMERCE_DW
GO

CREATE VIEW V_SUPPLIER_ANALYSIS AS
SELECT DSP.NAME AS SUPPLIER,
	   T.YEAR AS YEAR,
	   SUM(F.AMOUNT) AS AMOUNT,
	   SUM(F.ITEM_TOTAL) AS SELLER_TOTAL

	   FROM COMERCIO_STAGE.DBO.ST_FACT F

	   INNER JOIN DBO.DIM_SUPPLIER DSP
	   ON F.IDSUPPLIER = FN.IDSUPPLIER

	   INNER JOIN DBO.DIM_TIME T
	   ON (CONVERT(VARCHAR, T.DATE, 102) =
	   CONVERT(VARCHAR, F.DATE, 102))

	   GROUP BY DSP.NAME, T.YEAR
	   GO

SELECT DISTINCT DIM_TIME.YEAR
FROM            DIM_TIME INNER JOIN
                         FACT ON DIM_TIME.IDSK = FACT.IDTIME

SELECT        SUPPLIER, YEAR, AMOUNT, SALE_TOTAL
FROM            V_SUPPLIER_ANALYSIS
WHERE (YEAR = @YEAR)
ORDER BY SUPPLIER

SELECT        SUPPLIER, YEAR, AMOUNT, SALE_TOTAL
FROM            V_SUPPLIER_ANALYSIS
WHERE YEAR IN ( @YEAR )
ORDER BY SUPPLIER