USE COMMERCE_OLTP
GO

SELECT * FROM CUSTOMER
SELECT * FROM CUSTOMER_ADDRESS
SELECT * FROM CATEGORY
SELECT * FROM SUPPLIER
SELECT * FROM PRODUCT
SELECT * FROM SELLER
SELECT * FROM PAYMENT_FORM
SELECT * FROM INVOICE
GO

SELECT COUNT(*) FROM INVOICE